# Generated by Django 4.1 on 2022-09-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_note_text_alter_note_title_noteversion_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="note",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="notes.note",
            ),
        ),
    ]
