# Generated by Django 4.1 on 2022-09-14 11:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_alter_comment_note_alter_comment_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=31),
        ),
    ]
