# Generated by Django 4.1 on 2022-09-16 04:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_tag_note_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=32, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
